import { ElectricityProvider } from '../types';

export const NATIONAL_PROVIDER_REGISTRY: Record<string, ElectricityProvider> = {
  kseb: {
    id: 'kseb',
    legalName: 'Kerala State Electricity Board Limited',
    displayName: 'KSEB',
    shortName: 'KSEB',
    aliases: ['KSEBL', 'K.S.E.B', 'Kerala Electricity Board', 'Kerala Vidyuthi'],
    state: 'Kerala',
    stateCode: 'KL',
    unionTerritory: false,
    serviceAreas: ['Kerala Statewide', 'Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Thrissur', 'Kollam'],
    providerType: 'state_discom',
    regulatorId: 'kserc',
    website: 'https://kseb.in',
    consumerPortal: 'https://wss.kseb.in/selfservices',
    billingPortal: 'https://wss.kseb.in/selfservices/quickpay',
    tariffSourceUrl: 'https://erckerala.org/tariff-orders',
    supportLanguages: ['en', 'ml'],
    active: true,
    lastVerified: '2024-11-01',
    verificationStatus: 'verified',
    coverageStatus: 'FULL',
    supportedTariffCategories: ['LT-1A', 'LT-1B'],
    billingCycles: ['BIMONTHLY', 'MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: true,
      supportsSolarNetMetering: true,
      supportsDemandCharges: false,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['kerala', 'kseb', 'ksebl', 'trivandrum', 'cochin', 'kochi', 'malabar', 'lt-1a'],
    sampleBillIdentifierPattern: '(kseb|kerala\\s+state\\s+electricity|consumer\\s*no\\s*:\\s*11\\d{11}|wss\\.kseb\\.in)',
  },

  bescom: {
    id: 'bescom',
    legalName: 'Bangalore Electricity Supply Company Limited',
    displayName: 'BESCOM (Bangalore)',
    shortName: 'BESCOM',
    aliases: ['B.E.S.C.O.M', 'Bangalore Electricity', 'Bengaluru Vidyut'],
    state: 'Karnataka',
    stateCode: 'KA',
    unionTerritory: false,
    serviceAreas: ['Bangalore Urban', 'Bangalore Rural', 'Kolar', 'Chikkaballapura', 'Ramanagara', 'Tumakuru', 'Chitradurga', 'Davanagere'],
    providerType: 'state_discom',
    regulatorId: 'kerc',
    website: 'https://bescom.karnataka.gov.in',
    consumerPortal: 'https://bescom.co.in/SCP/MyHome.aspx',
    billingPortal: 'https://bescom.co.in/SCP/MyAccount/QuickPayment.aspx',
    tariffSourceUrl: 'https://kerc.karnataka.gov.in/tarifforders',
    supportLanguages: ['en', 'kn'],
    active: true,
    lastVerified: '2024-06-01',
    verificationStatus: 'verified',
    coverageStatus: 'FULL',
    supportedTariffCategories: ['LT-2(a)', 'LT-2(b)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: true,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: true,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['bangalore', 'bengaluru', 'karnataka', 'bescom', 'kerc', 'lt-2a', 'gruha jyothi'],
    sampleBillIdentifierPattern: '(bescom|bangalore\\s+electricity|bescom\\.co\\.in|account\\s*id\\s*:\\s*\\d{10})',
  },

  mescom: {
    id: 'mescom',
    legalName: 'Mangalore Electricity Supply Company Limited',
    displayName: 'MESCOM (Mangalore)',
    shortName: 'MESCOM',
    aliases: ['Mangalore Electricity'],
    state: 'Karnataka',
    stateCode: 'KA',
    serviceAreas: ['Dakshina Kannada', 'Udupi', 'Shivamogga', 'Chikkamagaluru'],
    providerType: 'state_discom',
    regulatorId: 'kerc',
    website: 'https://mescom.karnataka.gov.in',
    tariffSourceUrl: 'https://kerc.karnataka.gov.in/tarifforders',
    supportLanguages: ['en', 'kn'],
    active: true,
    lastVerified: '2024-06-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['LT-2(a)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['mangalore', 'udupi', 'karnataka', 'mescom'],
  },

  hescom: {
    id: 'hescom',
    legalName: 'Hubli Electricity Supply Company Limited',
    displayName: 'HESCOM (Hubli)',
    shortName: 'HESCOM',
    aliases: ['Hubli Electricity'],
    state: 'Karnataka',
    stateCode: 'KA',
    serviceAreas: ['Dharwad', 'Belagavi', 'Vijayapura', 'Bagalkote', 'Gadag', 'Haveri', 'Uttara Kannada'],
    providerType: 'state_discom',
    regulatorId: 'kerc',
    website: 'https://hescom.karnataka.gov.in',
    tariffSourceUrl: 'https://kerc.karnataka.gov.in/tarifforders',
    supportLanguages: ['en', 'kn'],
    active: true,
    lastVerified: '2024-06-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['LT-2(a)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['hubli', 'dharwad', 'belgaum', 'belagavi', 'hescom', 'karnataka'],
  },

  gescom: {
    id: 'gescom',
    legalName: 'Gulbarga Electricity Supply Company Limited',
    displayName: 'GESCOM (Kalaburagi)',
    shortName: 'GESCOM',
    aliases: ['Gulbarga Electricity', 'Kalaburagi Electricity'],
    state: 'Karnataka',
    stateCode: 'KA',
    serviceAreas: ['Kalaburagi', 'Bidar', 'Yadgir', 'Raichur', 'Koppal', 'Ballari', 'Vijayanagara'],
    providerType: 'state_discom',
    regulatorId: 'kerc',
    website: 'https://gescom.karnataka.gov.in',
    tariffSourceUrl: 'https://kerc.karnataka.gov.in/tarifforders',
    supportLanguages: ['en', 'kn'],
    active: true,
    lastVerified: '2024-06-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['LT-2(a)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['gulbarga', 'kalaburagi', 'bellary', 'gescom', 'karnataka'],
  },

  'cesc-mysore': {
    id: 'cesc-mysore',
    legalName: 'Chamundeshwari Electricity Supply Corporation Limited',
    displayName: 'CESC (Mysuru)',
    shortName: 'CESC Mysuru',
    aliases: ['Chamundeshwari Electricity', 'Mysore Electricity'],
    state: 'Karnataka',
    stateCode: 'KA',
    serviceAreas: ['Mysuru', 'Mandya', 'Chamarajanagara', 'Hassan', 'Kodagu'],
    providerType: 'state_discom',
    regulatorId: 'kerc',
    website: 'https://cescmysore.karnataka.gov.in',
    tariffSourceUrl: 'https://kerc.karnataka.gov.in/tarifforders',
    supportLanguages: ['en', 'kn'],
    active: true,
    lastVerified: '2024-06-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['LT-2(a)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['mysore', 'mysuru', 'coorg', 'hassan', 'cesc mysore', 'karnataka'],
  },

  msedcl: {
    id: 'msedcl',
    legalName: 'Maharashtra State Electricity Distribution Company Limited',
    displayName: 'MSEDCL (Mahavitaran)',
    shortName: 'MSEDCL',
    aliases: ['Mahavitaran', 'MahaDiscom', 'MSEB', 'Maharashtra State Electricity Board'],
    state: 'Maharashtra',
    stateCode: 'MH',
    unionTerritory: false,
    serviceAreas: ['Maharashtra Statewide (excl. Mumbai island city)', 'Pune', 'Nagpur', 'Nashik', 'Thane', 'Navi Mumbai', 'Aurangabad'],
    providerType: 'state_discom',
    regulatorId: 'merc',
    website: 'https://www.mahadiscom.in',
    consumerPortal: 'https://wss.mahadiscom.in/wss/wss',
    billingPortal: 'https://wss.mahadiscom.in/wss/wss?uiActionName=getViewPayBill',
    tariffSourceUrl: 'https://www.merc.gov.in/orders-fac-orders',
    supportLanguages: ['en', 'mr'],
    active: true,
    lastVerified: '2024-04-01',
    verificationStatus: 'verified',
    coverageStatus: 'FULL',
    supportedTariffCategories: ['LT-1 (Residential)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: true,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: true,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: true,
    },
    searchKeywords: ['maharashtra', 'msedcl', 'mahavitaran', 'pune', 'nagpur', 'thane', 'nashik', 'lt-1'],
    sampleBillIdentifierPattern: '(mahavitaran|msedcl|mahadiscom|consumer\\s*no\\s*:\\s*\\d{12}|consumer\\s*no\\s*\\d{12})',
  },

  'adani-mumbai': {
    id: 'adani-mumbai',
    legalName: 'Adani Electricity Mumbai Limited',
    displayName: 'Adani Electricity (Mumbai)',
    shortName: 'Adani Electricity',
    aliases: ['AEML', 'Reliance Energy Mumbai', 'BSES Mumbai'],
    state: 'Maharashtra',
    stateCode: 'MH',
    serviceAreas: ['Mumbai Suburbs', 'Mira-Bhayander'],
    providerType: 'private_licensee',
    regulatorId: 'merc',
    website: 'https://www.adanielectricity.com',
    consumerPortal: 'https://www.adanielectricity.com/quick-pay',
    tariffSourceUrl: 'https://www.merc.gov.in/orders-fac-orders',
    supportLanguages: ['en', 'mr', 'hi'],
    active: true,
    lastVerified: '2024-04-01',
    verificationStatus: 'verified',
    coverageStatus: 'PARTIAL',
    supportedTariffCategories: ['LT-1 (Residential)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: true,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: false,
      supportsWheelingCharges: true,
    },
    searchKeywords: ['mumbai', 'adani', 'aeml', 'andheri', 'borivali', 'bandra', 'suburbs'],
    sampleBillIdentifierPattern: '(adani\\s+electricity|aeml|adanielectricity\\.com)',
  },

  'tata-mumbai': {
    id: 'tata-mumbai',
    legalName: 'Tata Power Company Limited (Distribution)',
    displayName: 'Tata Power (Mumbai)',
    shortName: 'Tata Power Mumbai',
    aliases: ['TPCL Mumbai'],
    state: 'Maharashtra',
    stateCode: 'MH',
    serviceAreas: ['Mumbai City & Suburbs'],
    providerType: 'private_licensee',
    regulatorId: 'merc',
    website: 'https://www.tatapower.com',
    tariffSourceUrl: 'https://www.merc.gov.in/orders-fac-orders',
    supportLanguages: ['en', 'mr'],
    active: true,
    lastVerified: '2024-04-01',
    verificationStatus: 'verified',
    coverageStatus: 'PARTIAL',
    supportedTariffCategories: ['LT-1 (Residential)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: true,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: false,
      supportsWheelingCharges: true,
    },
    searchKeywords: ['mumbai', 'tata power', 'tata power mumbai'],
  },

  'best-mumbai': {
    id: 'best-mumbai',
    legalName: 'Brihanmumbai Electric Supply and Transport Undertaking',
    displayName: 'BEST (Mumbai Island City)',
    shortName: 'BEST Undertaking',
    aliases: ['B.E.S.T', 'BEST Electricity'],
    state: 'Maharashtra',
    stateCode: 'MH',
    serviceAreas: ['Mumbai Island City (Colaba to Sion/Mahim)'],
    providerType: 'municipal_utility',
    regulatorId: 'merc',
    website: 'https://www.bestundertaking.com',
    tariffSourceUrl: 'https://www.merc.gov.in/orders-fac-orders',
    supportLanguages: ['en', 'mr'],
    active: true,
    lastVerified: '2024-04-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['LT-1 (Residential)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: false,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['mumbai south', 'colaba', 'dadar', 'best undertaking', 'mumbai island'],
  },

  tpddl: {
    id: 'tpddl',
    legalName: 'Tata Power Delhi Distribution Limited',
    displayName: 'Tata Power-DDL (Delhi)',
    shortName: 'TPDDL',
    aliases: ['NDPL', 'North Delhi Power Limited', 'Tata Power Delhi'],
    state: 'Delhi',
    stateCode: 'DL',
    unionTerritory: true,
    serviceAreas: ['North Delhi', 'North-West Delhi', 'Parts of Central Delhi'],
    providerType: 'private_licensee',
    regulatorId: 'derc',
    website: 'https://www.tatapower-ddl.com',
    consumerPortal: 'https://www.tatapower-ddl.com/paybill/quickpay.aspx',
    tariffSourceUrl: 'https://www.derc.gov.in/tarifforders',
    supportLanguages: ['en', 'hi'],
    active: true,
    lastVerified: '2024-07-01',
    verificationStatus: 'verified',
    coverageStatus: 'FULL',
    supportedTariffCategories: ['Domestic (Residential)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: true,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: true,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['delhi', 'tpddl', 'rohini', 'pitampura', 'model town', 'tata power delhi'],
    sampleBillIdentifierPattern: '(tata\\s+power\\s+delhi|tpddl|tatapower-ddl\\.com|ca\\s*number\\s*:\\s*\\d{11})',
  },

  brpl: {
    id: 'brpl',
    legalName: 'BSES Rajdhani Power Limited',
    displayName: 'BSES Rajdhani (Delhi)',
    shortName: 'BRPL',
    aliases: ['BSES Delhi South', 'BSES Rajdhani'],
    state: 'Delhi',
    stateCode: 'DL',
    unionTerritory: true,
    serviceAreas: ['South Delhi', 'West Delhi'],
    providerType: 'private_licensee',
    regulatorId: 'derc',
    website: 'https://www.bsesdelhi.com',
    consumerPortal: 'https://www.bsesdelhi.com/web/brpl/quick-pay',
    tariffSourceUrl: 'https://www.derc.gov.in/tarifforders',
    supportLanguages: ['en', 'hi'],
    active: true,
    lastVerified: '2024-07-01',
    verificationStatus: 'verified',
    coverageStatus: 'FULL',
    supportedTariffCategories: ['Domestic (Residential)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: true,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: true,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['delhi south', 'delhi west', 'bses', 'brpl', 'rajdhani', 'dwarka', 'saket'],
    sampleBillIdentifierPattern: '(bses\\s+rajdhani|brpl|bsesdelhi\\.com)',
  },

  bypl: {
    id: 'bypl',
    legalName: 'BSES Yamuna Power Limited',
    displayName: 'BSES Yamuna (Delhi)',
    shortName: 'BYPL',
    aliases: ['BSES Delhi East', 'BSES Yamuna'],
    state: 'Delhi',
    stateCode: 'DL',
    unionTerritory: true,
    serviceAreas: ['East Delhi', 'Central Delhi'],
    providerType: 'private_licensee',
    regulatorId: 'derc',
    website: 'https://www.bsesdelhi.com',
    tariffSourceUrl: 'https://www.derc.gov.in/tarifforders',
    supportLanguages: ['en', 'hi'],
    active: true,
    lastVerified: '2024-07-01',
    verificationStatus: 'verified',
    coverageStatus: 'PARTIAL',
    supportedTariffCategories: ['Domestic (Residential)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: true,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: true,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['delhi east', 'bypl', 'yamuna', 'laxmi nagar', 'mayur vihar'],
    sampleBillIdentifierPattern: '(bses\\s+yamuna|bypl)',
  },

  tangedco: {
    id: 'tangedco',
    legalName: 'Tamil Nadu Power Distribution Corporation Limited',
    displayName: 'TANGEDCO / TNPDCL (Tamil Nadu)',
    shortName: 'TANGEDCO',
    aliases: ['TNPDCL', 'TNEB', 'Tamil Nadu Electricity Board'],
    state: 'Tamil Nadu',
    stateCode: 'TN',
    unionTerritory: false,
    serviceAreas: ['Tamil Nadu Statewide', 'Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem'],
    providerType: 'state_discom',
    regulatorId: 'tnerc',
    website: 'https://www.tnebnet.org',
    consumerPortal: 'https://www.tnebnet.org/qpay',
    tariffSourceUrl: 'https://www.tnerc.gov.in/orders',
    supportLanguages: ['en', 'ta'],
    active: true,
    lastVerified: '2024-07-01',
    verificationStatus: 'verified',
    coverageStatus: 'FULL',
    supportedTariffCategories: ['Tariff I-A (Domestic)'],
    billingCycles: ['BIMONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['tamil nadu', 'chennai', 'coimbatore', 'tneb', 'tangedco', 'tnpdcl', 'madurai'],
    sampleBillIdentifierPattern: '(tangedco|tnpdcl|tneb|service\\s*number\\s*:\\s*\\d{10,12})',
  },

  tsspdcl: {
    id: 'tsspdcl',
    legalName: 'Southern Power Distribution Company of Telangana Limited',
    displayName: 'TSSPDCL (Hyderabad / South Telangana)',
    shortName: 'TSSPDCL',
    aliases: ['Telangana Southern Power', 'Hyderabad Electricity'],
    state: 'Telangana',
    stateCode: 'TS',
    unionTerritory: false,
    serviceAreas: ['Hyderabad', 'Rangareddy', 'Medchal-Malkajgiri', 'Mahabubnagar', 'Nalgonda', 'Medak'],
    providerType: 'state_discom',
    regulatorId: 'tserc',
    website: 'https://www.tssouthernpower.com',
    consumerPortal: 'https://www.tssouthernpower.com/onlinebillpayment',
    tariffSourceUrl: 'https://tserc.gov.in/tarifforders',
    supportLanguages: ['en', 'te'],
    active: true,
    lastVerified: '2024-05-01',
    verificationStatus: 'verified',
    coverageStatus: 'FULL',
    supportedTariffCategories: ['LT-I (Domestic)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['hyderabad', 'telangana', 'tsspdcl', 'secunderabad', 'cyberabad'],
    sampleBillIdentifierPattern: '(tsspdcl|tssouthernpower|usc\\s*no\\s*:\\s*\\d{8,10})',
  },

  pvvnl: {
    id: 'pvvnl',
    legalName: 'Pashchimanchal Vidyut Vitran Nigam Limited (UPPCL)',
    displayName: 'PVVNL (Western UP / Meerut / Noida)',
    shortName: 'PVVNL',
    aliases: ['UPPCL West', 'Paschimanchal Vidyut', 'Meerut DISCOM'],
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    unionTerritory: false,
    serviceAreas: ['Meerut', 'Noida', 'Ghaziabad', 'Bulandshahr', 'Saharanpur', 'Muzaffarnagar', 'Moradabad'],
    providerType: 'state_discom',
    regulatorId: 'uperc',
    website: 'https://pvvnl.org',
    consumerPortal: 'https://www.upenergy.in',
    tariffSourceUrl: 'https://www.uperc.org/tarifforders',
    supportLanguages: ['en', 'hi'],
    active: true,
    lastVerified: '2024-06-01',
    verificationStatus: 'verified',
    coverageStatus: 'FULL',
    supportedTariffCategories: ['LMV-1 (Domestic Light, Fan & Power)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: true,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['noida', 'ghaziabad', 'meerut', 'pvvnl', 'uppcl', 'uttar pradesh'],
    sampleBillIdentifierPattern: '(pvvnl|uppcl|upenergy\\.in|account\\s*no\\s*:\\s*\\d{10})',
  },

  wbsedcl: {
    id: 'wbsedcl',
    legalName: 'West Bengal State Electricity Distribution Company Limited',
    displayName: 'WBSEDCL (West Bengal)',
    shortName: 'WBSEDCL',
    aliases: ['WBSEB', 'West Bengal Vidyut'],
    state: 'West Bengal',
    stateCode: 'WB',
    unionTerritory: false,
    serviceAreas: ['West Bengal Statewide (except CESC Kolkata area)', 'Howrah', 'Siliguri', 'Durgapur', 'Asansol'],
    providerType: 'state_discom',
    regulatorId: 'wberc',
    website: 'https://www.wbsedcl.in',
    consumerPortal: 'https://www.wbsedcl.in/portal/wbsedcl/epay.jsp',
    tariffSourceUrl: 'https://wberc.gov.in/tarifforders',
    supportLanguages: ['en', 'bn'],
    active: true,
    lastVerified: '2024-05-01',
    verificationStatus: 'verified',
    coverageStatus: 'PARTIAL',
    supportedTariffCategories: ['Domestic (Urban/Rural)'],
    billingCycles: ['QUARTERLY', 'MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: true,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['west bengal', 'wbsedcl', 'wbseb', 'siliguri', 'howrah'],
    sampleBillIdentifierPattern: '(wbsedcl|west\\s+bengal\\s+state\\s+electricity|consumer\\s*id\\s*:\\s*\\d{9})',
  },

  'cesc-kolkata': {
    id: 'cesc-kolkata',
    legalName: 'CESC Limited (Kolkata)',
    displayName: 'CESC (Kolkata & Howrah)',
    shortName: 'CESC Kolkata',
    aliases: ['Calcutta Electric Supply Corporation', 'CESC Bengal'],
    state: 'West Bengal',
    stateCode: 'WB',
    serviceAreas: ['Kolkata', 'Howrah', 'Hooghly'],
    providerType: 'private_licensee',
    regulatorId: 'wberc',
    website: 'https://www.cesc.co.in',
    consumerPortal: 'https://www.cesc.co.in/quickpayment',
    tariffSourceUrl: 'https://wberc.gov.in/tarifforders',
    supportLanguages: ['en', 'bn', 'hi'],
    active: true,
    lastVerified: '2024-05-01',
    verificationStatus: 'verified',
    coverageStatus: 'PARTIAL',
    supportedTariffCategories: ['Domestic LT'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: false,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['kolkata', 'calcutta', 'cesc', 'howrah', 'bengal'],
    sampleBillIdentifierPattern: '(cesc\\s+limited|cesc\\.co\\.in|customer\\s*id\\s*:\\s*\\d{11})',
  },

  // Remaining representative state and UT utilities covering all jurisdictions
  dgvcl: {
    id: 'dgvcl',
    legalName: 'Dakshin Gujarat Vij Company Limited',
    displayName: 'DGVCL (South Gujarat / Surat)',
    shortName: 'DGVCL',
    aliases: ['GEB South', 'Surat Vidyut'],
    state: 'Gujarat',
    stateCode: 'GJ',
    serviceAreas: ['Surat', 'Navsari', 'Valsad', 'Tapi', 'Bharuch'],
    providerType: 'state_discom',
    regulatorId: 'gerc',
    website: 'https://www.dgvcl.com',
    tariffSourceUrl: 'https://gercin.org/tarifforders',
    supportLanguages: ['en', 'gu'],
    active: true,
    lastVerified: '2024-04-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['RGP (Residential General Purpose)'],
    billingCycles: ['BIMONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['gujarat', 'surat', 'dgvcl', 'geb'],
  },

  jvvnl: {
    id: 'jvvnl',
    legalName: 'Jaipur Vidyut Vitran Nigam Limited',
    displayName: 'JVVNL (Jaipur Discom)',
    shortName: 'JVVNL',
    aliases: ['Jaipur Vidyut', 'Rajasthan Discom'],
    state: 'Rajasthan',
    stateCode: 'RJ',
    serviceAreas: ['Jaipur', 'Dausa', 'Alwar', 'Bharatpur', 'Kota'],
    providerType: 'state_discom',
    regulatorId: 'rerc',
    website: 'https://energy.rajasthan.gov.in/jvvnl',
    tariffSourceUrl: 'https://rerc.rajasthan.gov.in/orders',
    supportLanguages: ['en', 'hi'],
    active: true,
    lastVerified: '2024-05-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['Domestic LT-1'],
    billingCycles: ['MONTHLY', 'BIMONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['rajasthan', 'jaipur', 'jvvnl', 'kota'],
  },

  pspcl: {
    id: 'pspcl',
    legalName: 'Punjab State Power Corporation Limited',
    displayName: 'PSPCL (Punjab)',
    shortName: 'PSPCL',
    aliases: ['PSEB', 'Punjab Electricity Board'],
    state: 'Punjab',
    stateCode: 'PB',
    serviceAreas: ['Punjab Statewide', 'Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala'],
    providerType: 'state_discom',
    regulatorId: 'pserc',
    website: 'https://pspcl.in',
    tariffSourceUrl: 'https://pserc.punjab.gov.in/tarifforders',
    supportLanguages: ['en', 'pa'],
    active: true,
    lastVerified: '2024-06-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['Domestic Supply (DS)'],
    billingCycles: ['BIMONTHLY', 'MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['punjab', 'pspcl', 'pseb', 'amritsar', 'ludhiana', 'patiala'],
  },

  dhbvn: {
    id: 'dhbvn',
    legalName: 'Dakshin Haryana Bijli Vitran Nigam',
    displayName: 'DHBVN (South Haryana / Gurugram)',
    shortName: 'DHBVN',
    aliases: ['Haryana Bijli South', 'Gurgaon Electricity'],
    state: 'Haryana',
    stateCode: 'HR',
    serviceAreas: ['Gurugram', 'Faridabad', 'Hisar', 'Rewari', 'Sirsa'],
    providerType: 'state_discom',
    regulatorId: 'herc',
    website: 'https://www.dhbvn.org.in',
    tariffSourceUrl: 'https://herc.gov.in/tarifforders',
    supportLanguages: ['en', 'hi'],
    active: true,
    lastVerified: '2024-04-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['Domestic Supply (DS)'],
    billingCycles: ['BIMONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['haryana', 'gurgaon', 'gurugram', 'faridabad', 'dhbvn'],
  },

  apspdcl: {
    id: 'apspdcl',
    legalName: 'Southern Power Distribution Company of AP Limited',
    displayName: 'APSPDCL (Andhra Pradesh South)',
    shortName: 'APSPDCL',
    aliases: ['AP Southern Power', 'Tirupati Electricity'],
    state: 'Andhra Pradesh',
    stateCode: 'AP',
    serviceAreas: ['Tirupati', 'Nellore', 'Kadapa', 'Anantapur', 'Kurnool'],
    providerType: 'state_discom',
    regulatorId: 'aperc',
    website: 'https://www.apspdcl.in',
    tariffSourceUrl: 'https://aperc.gov.in/tarifforders',
    supportLanguages: ['en', 'te'],
    active: true,
    lastVerified: '2024-04-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['LT-Category I (Domestic)'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: true,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['andhra pradesh', 'tirupati', 'apspdcl', 'amaravati'],
  },

  'chandigarh-elec': {
    id: 'chandigarh-elec',
    legalName: 'Electricity Department, Union Territory of Chandigarh',
    displayName: 'Electricity Department Chandigarh',
    shortName: 'UT Chandigarh Elec',
    aliases: ['Chandigarh Electricity Board'],
    state: 'Chandigarh',
    stateCode: 'CH',
    unionTerritory: true,
    serviceAreas: ['Chandigarh UT City'],
    providerType: 'ut_utility',
    regulatorId: 'jerc_goa_ut',
    website: 'https://chandigarh.gov.in',
    tariffSourceUrl: 'https://jercuts.gov.in/orders',
    supportLanguages: ['en', 'hi', 'pa'],
    active: true,
    lastVerified: '2024-05-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['Domestic LT'],
    billingCycles: ['BIMONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: false,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['chandigarh', 'tricity'],
  },

  'goa-elec': {
    id: 'goa-elec',
    legalName: 'Electricity Department, Government of Goa',
    displayName: 'Goa Electricity Department',
    shortName: 'Goa Electricity',
    aliases: ['GED', 'Goa Vidyut'],
    state: 'Goa',
    stateCode: 'GA',
    serviceAreas: ['North Goa', 'South Goa', 'Panaji', 'Margao', 'Vasco'],
    providerType: 'state_discom',
    regulatorId: 'jerc_goa_ut',
    website: 'https://goaelectricity.gov.in',
    tariffSourceUrl: 'https://jercuts.gov.in/orders',
    supportLanguages: ['en', 'kok'],
    active: true,
    lastVerified: '2024-05-01',
    verificationStatus: 'verified',
    coverageStatus: 'CALCULATOR_ONLY',
    supportedTariffCategories: ['Tariff (LTD) Domestic'],
    billingCycles: ['MONTHLY'],
    capabilities: {
      supportsMeterReading: true,
      supportsToD: false,
      supportsSolarNetMetering: true,
      supportsDemandCharges: true,
      supportsPrepaid: false,
      supportsPrediction: true,
      supportsBudgetInverse: true,
      supportsSubsidies: false,
      supportsWheelingCharges: false,
    },
    searchKeywords: ['goa', 'panaji', 'margao', 'goa electricity'],
  },
};

// Static pre-sorted provider array and pre-computed search index for instant zero-allocation lookup
const STATUS_PRIORITY: Record<string, number> = {
  FULL: 0,
  PARTIAL: 1,
  CALCULATOR_ONLY: 2,
  REQUESTED: 3,
};

const CACHED_ALL_PROVIDERS: ElectricityProvider[] = Object.values(NATIONAL_PROVIDER_REGISTRY).sort(
  (a, b) => (STATUS_PRIORITY[a.coverageStatus] ?? 99) - (STATUS_PRIORITY[b.coverageStatus] ?? 99)
);

const SEARCH_INDEX = CACHED_ALL_PROVIDERS.map((p) => ({
  provider: p,
  haystack: `${p.id} ${p.shortName.toLowerCase()} ${p.displayName.toLowerCase()} ${p.legalName.toLowerCase()} ${p.state.toLowerCase()} ${p.stateCode.toLowerCase()} ${p.aliases.join(' ').toLowerCase()} ${p.serviceAreas.join(' ').toLowerCase()} ${p.searchKeywords.join(' ')}`,
}));

/**
 * Fast search index and lookup utilities
 */
export function getProviderById(id: string): ElectricityProvider | undefined {
  if (!id) return undefined;
  return NATIONAL_PROVIDER_REGISTRY[id.toLowerCase()];
}

export function getAllProviders(): ElectricityProvider[] {
  return CACHED_ALL_PROVIDERS;
}

export function getProvidersByState(stateOrCode: string): ElectricityProvider[] {
  const norm = stateOrCode.trim().toLowerCase();
  return CACHED_ALL_PROVIDERS.filter(
    p => p.state.toLowerCase() === norm || p.stateCode.toLowerCase() === norm
  );
}

export function searchProviders(query: string): ElectricityProvider[] {
  if (!query || !query.trim()) return CACHED_ALL_PROVIDERS;
  const q = query.trim().toLowerCase();
  const results: ElectricityProvider[] = [];
  for (let i = 0; i < SEARCH_INDEX.length; i++) {
    if (SEARCH_INDEX[i].haystack.includes(q)) {
      results.push(SEARCH_INDEX[i].provider);
    }
  }
  return results;
}

export function getNationalCoverageStats() {
  const providers = getAllProviders();
  const states = new Set(providers.map(p => p.state));
  const full = providers.filter(p => p.coverageStatus === 'FULL').length;
  const partial = providers.filter(p => p.coverageStatus === 'PARTIAL').length;
  const calculatorOnly = providers.filter(p => p.coverageStatus === 'CALCULATOR_ONLY').length;

  return {
    totalProviders: providers.length,
    coveredStates: states.size,
    fullCoverageCount: full,
    partialCoverageCount: partial,
    calculatorOnlyCount: calculatorOnly,
  };
}
