import { ElectricityRegulator } from '../types';

export const REGULATOR_REGISTRY: Record<string, ElectricityRegulator> = {
  kserc: {
    id: 'kserc',
    name: 'Kerala State Electricity Regulatory Commission',
    shortName: 'KSERC',
    jurisdiction: 'Kerala',
    type: 'SERC',
    website: 'https://erckerala.org',
    tariffPageUrl: 'https://erckerala.org/tariff-orders',
    lastVerified: '2024-11-01',
  },
  kerc: {
    id: 'kerc',
    name: 'Karnataka Electricity Regulatory Commission',
    shortName: 'KERC',
    jurisdiction: 'Karnataka',
    type: 'SERC',
    website: 'https://kerc.karnataka.gov.in',
    tariffPageUrl: 'https://kerc.karnataka.gov.in/tarifforders',
    lastVerified: '2024-06-01',
  },
  merc: {
    id: 'merc',
    name: 'Maharashtra Electricity Regulatory Commission',
    shortName: 'MERC',
    jurisdiction: 'Maharashtra',
    type: 'SERC',
    website: 'https://www.merc.gov.in',
    tariffPageUrl: 'https://www.merc.gov.in/orders-fac-orders',
    lastVerified: '2024-04-01',
  },
  derc: {
    id: 'derc',
    name: 'Delhi Electricity Regulatory Commission',
    shortName: 'DERC',
    jurisdiction: 'Delhi',
    type: 'SERC',
    website: 'https://www.derc.gov.in',
    tariffPageUrl: 'https://www.derc.gov.in/tarifforders',
    lastVerified: '2024-07-01',
  },
  tnerc: {
    id: 'tnerc',
    name: 'Tamil Nadu Electricity Regulatory Commission',
    shortName: 'TNERC',
    jurisdiction: 'Tamil Nadu',
    type: 'SERC',
    website: 'https://www.tnerc.gov.in',
    tariffPageUrl: 'https://www.tnerc.gov.in/orders',
    lastVerified: '2024-07-01',
  },
  tserc: {
    id: 'tserc',
    name: 'Telangana State Electricity Regulatory Commission',
    shortName: 'TSERC',
    jurisdiction: 'Telangana',
    type: 'SERC',
    website: 'https://tserc.gov.in',
    tariffPageUrl: 'https://tserc.gov.in/tarifforders',
    lastVerified: '2024-05-01',
  },
  aperc: {
    id: 'aperc',
    name: 'Andhra Pradesh Electricity Regulatory Commission',
    shortName: 'APERC',
    jurisdiction: 'Andhra Pradesh',
    type: 'SERC',
    website: 'https://aperc.gov.in',
    tariffPageUrl: 'https://aperc.gov.in/tarifforders',
    lastVerified: '2024-04-01',
  },
  uperc: {
    id: 'uperc',
    name: 'Uttar Pradesh Electricity Regulatory Commission',
    shortName: 'UPERC',
    jurisdiction: 'Uttar Pradesh',
    type: 'SERC',
    website: 'https://www.uperc.org',
    tariffPageUrl: 'https://www.uperc.org/tarifforders',
    lastVerified: '2024-06-01',
  },
  wberc: {
    id: 'wberc',
    name: 'West Bengal Electricity Regulatory Commission',
    shortName: 'WBERC',
    jurisdiction: 'West Bengal',
    type: 'SERC',
    website: 'https://wberc.gov.in',
    tariffPageUrl: 'https://wberc.gov.in/tarifforders',
    lastVerified: '2024-05-01',
  },
  gerc: {
    id: 'gerc',
    name: 'Gujarat Electricity Regulatory Commission',
    shortName: 'GERC',
    jurisdiction: 'Gujarat',
    type: 'SERC',
    website: 'https://gercin.org',
    tariffPageUrl: 'https://gercin.org/tarifforders',
    lastVerified: '2024-04-01',
  },
  rerc: {
    id: 'rerc',
    name: 'Rajasthan Electricity Regulatory Commission',
    shortName: 'RERC',
    jurisdiction: 'Rajasthan',
    type: 'SERC',
    website: 'https://rerc.rajasthan.gov.in',
    tariffPageUrl: 'https://rerc.rajasthan.gov.in/orders',
    lastVerified: '2024-05-01',
  },
  pserc: {
    id: 'pserc',
    name: 'Punjab State Electricity Regulatory Commission',
    shortName: 'PSERC',
    jurisdiction: 'Punjab',
    type: 'SERC',
    website: 'https://pserc.punjab.gov.in',
    tariffPageUrl: 'https://pserc.punjab.gov.in/tarifforders',
    lastVerified: '2024-06-01',
  },
  herc: {
    id: 'herc',
    name: 'Haryana Electricity Regulatory Commission',
    shortName: 'HERC',
    jurisdiction: 'Haryana',
    type: 'SERC',
    website: 'https://herc.gov.in',
    tariffPageUrl: 'https://herc.gov.in/tarifforders',
    lastVerified: '2024-04-01',
  },
  mperc: {
    id: 'mperc',
    name: 'Madhya Pradesh Electricity Regulatory Commission',
    shortName: 'MPERC',
    jurisdiction: 'Madhya Pradesh',
    type: 'SERC',
    website: 'https://mperc.in',
    tariffPageUrl: 'https://mperc.in/tarifforders',
    lastVerified: '2024-05-01',
  },
  berc: {
    id: 'berc',
    name: 'Bihar Electricity Regulatory Commission',
    shortName: 'BERC',
    jurisdiction: 'Bihar',
    type: 'SERC',
    website: 'https://berc.bih.nic.in',
    tariffPageUrl: 'https://berc.bih.nic.in/tarifforders',
    lastVerified: '2024-04-01',
  },
  oerc: {
    id: 'oerc',
    name: 'Odisha Electricity Regulatory Commission',
    shortName: 'OERC',
    jurisdiction: 'Odisha',
    type: 'SERC',
    website: 'https://oerc.gov.in',
    tariffPageUrl: 'https://oerc.gov.in/tarifforders',
    lastVerified: '2024-04-01',
  },
  aerc: {
    id: 'aerc',
    name: 'Assam Electricity Regulatory Commission',
    shortName: 'AERC',
    jurisdiction: 'Assam',
    type: 'SERC',
    website: 'https://aerc.gov.in',
    tariffPageUrl: 'https://aerc.gov.in/tarifforders',
    lastVerified: '2024-04-01',
  },
  jerc_goa_ut: {
    id: 'jerc_goa_ut',
    name: 'Joint Electricity Regulatory Commission for the State of Goa and Union Territories',
    shortName: 'JERC (Goa & UTs)',
    jurisdiction: 'Goa, Andaman & Nicobar, Chandigarh, Dadra & Nagar Haveli and Daman & Diu, Lakshadweep, Puducherry',
    type: 'JERC',
    website: 'https://jercuts.gov.in',
    tariffPageUrl: 'https://jercuts.gov.in/orders',
    lastVerified: '2024-05-01',
  },
  cea: {
    id: 'cea',
    name: 'Central Electricity Authority',
    shortName: 'CEA',
    jurisdiction: 'India (National)',
    type: 'AUTHORITY',
    website: 'https://cea.nic.in',
    tariffPageUrl: 'https://cea.nic.in/reports',
    lastVerified: '2024-01-01',
  },
  cerc: {
    id: 'cerc',
    name: 'Central Electricity Regulatory Commission',
    shortName: 'CERC',
    jurisdiction: 'India (Inter-state)',
    type: 'CERC',
    website: 'https://cercind.gov.in',
    tariffPageUrl: 'https://cercind.gov.in/tariff_orders.html',
    lastVerified: '2024-01-01',
  },
};

export function getRegulatorById(id: string): ElectricityRegulator | undefined {
  return REGULATOR_REGISTRY[id.toLowerCase()];
}

export function getAllRegulators(): ElectricityRegulator[] {
  return Object.values(REGULATOR_REGISTRY);
}
